# Generated by Django 5.0.7 on 2024-08-14 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointment_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='court',
            field=models.IntegerField(choices=[(1, 'Court 1'), (2, 'Court 2'), (3, 'Court 3'), (4, 'Court 4')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[(datetime.time(13, 0), '1:00 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(15, 0), '3:00 PM'), (datetime.time(16, 0), '4:00 PM')], default=datetime.time(13, 0)),
        ),
    ]
